# Generated by Django manually
from django.db import migrations, models
from django.conf import settings
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ragapp', '0009_conversation_is_favorite'),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.CharField(max_length=255)),
                ('upload_date', models.DateTimeField(auto_now_add=True)),
                ('file_size', models.IntegerField(default=0)),
                ('is_global', models.BooleanField(default=False)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='documents', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-upload_date'],
            },
        ),
        migrations.AddIndex(
            model_name='document',
            index=models.Index(fields=['user', 'filename'], name='ragapp_docu_user_id_4f09d3_idx'),
        ),
        migrations.AddIndex(
            model_name='document',
            index=models.Index(fields=['is_global'], name='ragapp_docu_is_glob_d1e2c3_idx'),
        ),
    ]
